services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        networks:
          - network1
    flask:
        build:
          context: .
          dockerfile: Dockerfile
        image: phdai_dev_rq_api:v2
        container_name: myapp
        ports:
          - '6060:80'
        networks:
          - network1
        depends_on:
          - rabbitmq
          - db
        volumes:
          - /var/docker-data/request-manager/static/images/after-hide:/app/static/images/afterHide
          - /var/docker-data/request-manager/static/images/before-hide:/app/static/images/beforeHide
          - /var/docker-data/request-manager/static/sounds/before-hide:/app/static/sounds/beforeHide
          - /var/docker-data/request-manager/static/sounds/after-hide:/app/static/sounds/afterHide
    db:
        image: postgres
        restart: always
        container_name: postgres
        ports:
          - '5433:5432'
        environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: a
           POSTGRES_DB: request_manager
        volumes:
          - db:/var/lib/postgresql/data
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
          - network1
networks:
  network1:
    name: flask
    external: true
volumes:
  db:
    driver: local
